affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
cxConfig:
  configJson: |
    {
      "com.liferay.client.extension.type.configuration.CETConfiguration~liferay-sample-theme-css-1" : {
        ":configurator:policy" : "force",
        "baseURL" : "${portalURL}/o/liferay-sample-theme-css-1",
        "buildTimestamp" : 1747768702891,
        "description" : "",
        "dxp.lxc.liferay.com.virtualInstanceId" : "default",
        "name" : "Liferay Sample Theme CSS 1",
        "projectId" : "liferaysamplethemecss1",
        "projectName" : "liferay-sample-theme-css-1",
        "properties" : [ ],
        "sourceCodeURL" : "",
        "type" : "themeCSS",
        "typeSettings" : [ "mainRTLURL=css/main_rtl.css", "clayRTLURL=css/clay_rtl.css", "clayURL=css/clay.css", "mainURL=css/main.css" ],
        "webContextPath" : "/liferay-sample-theme-css-1"
      }
    }
  domain: "liferaysamplethemecss1.docker.localhost"
  virtualInstanceId: "main.dxp.docker.localhost"
fullnameOverride: ""
image:
  pullPolicy: Always
  repository: registry:5000/liferaysamplethemecss1
  tag: latest
imagePullSecrets: []
ingress:
  annotations: {}
  className: ""
  hosts: []
  tls: []
livenessProbe:
  httpGet:
    path: /
    port: http
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
readinessProbe:
  httpGet:
    path: /
    port: http
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 80
  type: ClusterIP
serviceAccount:
  annotations: {}
  automount: true
  create: false
  name: ""
tolerations: []
volumeMounts: []
volumes: []
