apiVersion: v1
kind: ConfigMap
metadata:
    annotations:
        {{- include "liferay-client-extension.ext-provision-configmap.annotations" . | nindent 16 }}
    labels:
        {{- include "liferay-client-extension.ext-provision-configmap.labels" . | nindent 16 }}
    name: {{ include "liferay-client-extension.ext-provision-configmap.name" . }}
data:
    {{ .Release.Name }}.client-extension-config.json: {{ .Values.clientExtensionConfig.configJson | fromJson | toPrettyJson | quote }}
