resource "helm_release" "argocd" {
	chart="argo-cd"
	create_namespace=false
	depends_on=[
		kubernetes_namespace.argocd,
		kubernetes_secret.argocd_secret,
	]
	name="argocd"
	namespace=var.argocd_namespace
	repository="https://argoproj.github.io/argo-helm"
	upgrade_install=true
	values=[
		yamlencode(
			{
				applicationSet={
					resources={
						requests={
							cpu="500m"
							memory="1Gi"
						}
						limits={
							cpu="800m"
							memory="2Gi"
						}
					}
				}
				configs={
					cm={
						"application.resourceTrackingMethod"="annotation"
						"resource.exclusions"=yamlencode([
							{
								apiGroups=["*"]
								kinds=["ProviderConfigUsage"]
							},
							{
								apiGroups=["apiextensions.crossplane.io"]
								kinds=["ManagedResourceDefinition"]
							},
						])
					}
				}
				controller={
					resources={
						requests={
							cpu="200m"
							memory="512Mi"
						}
						limits={
							cpu="1000m"
							memory="1.5Gi"
						}
					}
				}
				installCRDs=true
				redis={
					resources={
						requests={
							cpu="100m"
							memory="256Mi"
						}
						limits={
							cpu="200m"
							memory="512Mi"
						}
					}
				}
				repoServer={
					resources={
						requests={
							cpu="200m"
							memory="256Mi"
						}
						limits={
							cpu="500m"
							memory="768Mi"
						}
					}
				}
				server={
					livenessProbe={
						initialDelaySeconds=90
						timeoutSeconds=5
					}
					readinessProbe={
						initialDelaySeconds=60
						timeoutSeconds=5
					}
					resources={
						requests={
							cpu="500m"
							memory="1Gi"
						}
						limits={
							cpu="1000m"
							memory="2Gi"
						}
					}
					service={
						type="ClusterIP"
					}
				}
			}),
	]
	version="9.1.5"
	wait=true
}
resource "kubernetes_namespace" "argocd" {
	metadata {
		labels=local.common_labels
		name=var.argocd_namespace
	}
}
resource "kubernetes_secret" "argocd_secret" {
	data={
		"server.secretkey"=random_password.argocd_server_secretkey.result
	}
	lifecycle {
		ignore_changes=[
			data,
		]
	}
	metadata {
		annotations={
			"meta.helm.sh/release-name"="argocd"
			"meta.helm.sh/release-namespace"=var.argocd_namespace
		}
		labels=merge(
			local.common_labels,
			{
				"app.kubernetes.io/managed-by"="Helm"
			})
		name="argocd-secret"
		namespace=var.argocd_namespace
	}
	type="Opaque"
}
resource "random_password" "argocd_server_secretkey" {
	length=32
	special=false
}