defaults:
    run:
        shell: bash
jobs:
    test-cloud-helm-chart:
        if: ${{github.repository == 'cloudnative-team/liferay-portal'}}
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            -   name: Create Kind cluster
                run: kind create cluster
            -   name: Run Helm test
                run: |
                    helm upgrade -i liferay --wait .

                    helm test liferay
                working-directory: ./cloud/helm
on:
    pull_request:
        paths:
            -   cloud/helm/**
    push:
        branches:
            -   master
        paths:
            -   cloud/**